version: '3'

services:
  db_postgres:
    image: postgres:15.2-alpine
    volumes:
    - ./db_data:/var/lib/postgresql/data
    env_file:
    - .env.docker
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.docker
    ports:
      - "8080:80"


